# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  log_momentum: True
  logging_interval: epoch
